[package]
name = "walker"
version = "0.5.0"
edition = "2024"

[dependencies]
gtk4 = { version = "^0.9.7", features = ["v4_6", "v4_12"] }
gtk4-layer-shell = "0.5.0"
protobuf = "3.7.2"
serde = { version = "1.0.219", features = ["derive"] }
mime_guess = "2.0"
chrono = { version = "0.4", features = ["clock"] }

[build-dependencies]
protobuf-codegen = "3.4"
protoc-bin-vendored = "3.0"
