force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
keep_open_modifier = "shift"    # won't close on activation, but rather select the next item in the list
exact_search_prefix = "'"       # disable fuzzy searching
theme = "default"               # theme to use
disable_mouse = false           # disable mouse (on input and list only)

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = "esc"
next = "down"
previous = "up"
toggle_exact = "ctrl e"
resume_last_query = "ctrl r"

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.archlinuxpkgs]
click = "install"
install = "enter"
remove = "ctrl d"

[providers.calc]
click = "copy"
copy = "enter"
save = "ctrl s"
delete = "ctrl d"

[providers.websearch]
click = "search"
search = "enter"

[providers.providerlist]
click = "activate"
activate = "enter"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date
click = "copy"
copy = "enter"
delete = "ctrl d"
edit = "ctrl o"
toggle_images_only = "ctrl i"

[providers.desktopapplications]
click = "start"
start = "enter"

[providers.files]
click = "open"
open = "enter"
open_dir = "ctrl enter"
copy_path = "ctrl shift C"
copy_file = "ctrl c"

[providers.todo]
click = "save"
save = "enter"
delete = "ctrl d"
mark_active = "ctrl a"
mark_done = "ctrl f"
clear = "ctrl shift X"

[providers.runner]
click = "start"
start = "enter"
start_terminal = "shift enter"

[providers.dmenu]
click = "select"
select = "enter"

[providers.symbols]
click = "copy"
copy = "enter"

[providers.unicode]
click = "copy"
copy = "enter"

[providers.menus]
click = "activate"
activate = "enter"
