force_keyboard_focus = false    # forces keyboard forcus to stay in Walker
close_when_open = true          # close walker when invoking while already opened
click_to_close = true           # closes walker if clicking outside of the main content area
selection_wrap = false          # wrap list if at bottom or top
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
keep_open_modifier = "shift"    # won't close on activation, but rather select the next item in the list
exact_search_prefix = "'"       # disable fuzzy searching
theme = "default"               # theme to use
disable_mouse = false           # disable mouse (on input and list only)

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl e"]
resume_last_query = ["ctrl r"]
quick_activate = ["F1", "F2", "F3", "F4"]

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "menus",
  "websearch",
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date

[providers.actions]
dmenu = [{ action = "select", default = true, bind = "Return" }]

providerlist = [
  { action = "activate", default = true, bind = "Return", after = "ClearReload" },
]

bluetooth = [
  { action = "find", bind = "ctrl f", after = "ClearReload" },
  { action = "trust", bind = "ctrl t", after = "Nothing", required_states = [
    "can_trust",
  ] },
  { action = "untrust", bind = "ctrl t", after = "Nothing", required_states = [
    "can_untrust",
  ] },
  { action = "pair", bind = "Return", after = "Nothing", required_states = [
    "can_pair",
  ] },
  { action = "remove", bind = "ctrl d", after = "Nothing", required_states = [
    "can_remove",
  ] },
  { action = "connect", bind = "Return", after = "Nothing", required_states = [
    "can_connect",
  ] },
  { action = "disconnect", bind = "Return", after = "Nothing", required_states = [
    "can_disconnect",
  ] },
]

archlinuxpkgs = [
  { action = "install", bind = "Return", default = true, required_states = [
    "available",
  ] },
  { action = "remove", bind = "Return", required_states = [
    "installed",
  ] },
]

calc = [
  { action = "copy", default = true, bind = "Return" },
  { action = "delete", bind = "ctrl d", after = "Reload", required_states = [
    "saved",
  ] },
  { action = "save", bind = "ctrl s", after = "ClearReload", required_states = [
    "current",
  ] },
]

websearch = [
  { action = "search", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload", required_states = [
    "history",
  ] },
]

desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "start_keep_open", label = "open+next", bind = "shift Return", after = "KeepOpen" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload", required_states = [
    "history",
  ] },
  { action = "toggle_pin", label = "pin", bind = "ctrl p", after = "Reload", required_states = [
    "unpinned",
  ] },
  { action = "toggle_pin", label = "un-pin", bind = "ctrl p", after = "Reload", required_states = [
    "pinned",
  ] },
]

files = [
  { action = "open", default = true, bind = "Return" },
  { action = "open_dir", label = "open dir", bind = "ctrl Return" },
  { action = "copy_path", label = "copy path", bind = "ctrl shift c" },
  { action = "copy_file", label = "copy file", bind = "ctrl c" },
]

todo = [
  { action = "save", default = true, bind = "Return", after = "ClearReload" },
  { action = "delete", bind = "ctrl d", after = "ClearReload" },
  { action = "active", bind = "ctrl a", after = "ClearReload" },
  { action = "done", bind = "ctrl f", after = "ClearReload" },
  { action = "clear", bind = "ctrl x", after = "ClearReload", global = true },
]

runner = [
  { action = "start", default = true, bind = "Return" },
  { action = "runterminal", label = "run in terminal", bind = "shift Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload", required_states = [
    "history",
  ] },
]

symbols = [
  { action = "copy", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload", required_states = [
    "history",
  ] },
]

unicode = [
  { action = "copy", default = true, bind = "Return" },
  { action = "erase_history", label = "clear hist", bind = "ctrl h", after = "Reload", required_states = [
    "history",
  ] },
]

clipboard = [
  { action = "copy", default = true, bind = "Return" },
  { action = "remove", bind = "ctrl d", after = "ClearReload" },
  { action = "remove_all", label = "clear", bind = "ctrl shift d", after = "ClearReload" },
  { action = "toggle_images", label = "toggle images", bind = "ctrl i", after = "ClearReload" },
  { action = "edit", bind = "ctrl o" },
]
